<section>
    <div id="rev_slider_26_1_wrapper" class="rev_slider_wrapper fullscreen-container" data-alias="mask-showcase" data-source="gallery" style="background: rgb(170, 170, 170); padding: 0px; max-height: none; overflow: visible; height: 567px;">
        <!-- START REVOLUTION SLIDER 5.4.1 fullscreen mode -->
        <div id="rev_slider_26_1" class="rev_slider fullscreenbanner tiny_bullet_slider revslider-initialised tp-simpleresponsive rev_redraw_on_blurfocus" style="max-height: none; margin-top: 0px; margin-bottom: 0px; height: 567px;" data-version="5.4.1" data-slideactive="rs-73">
            <ul class="tp-revslider-mainul" style="visibility: visible; display: block; overflow: hidden; width: 1324px; height: 100%; max-height: none; left: 0px;">
                <!-- SLIDE  -->
                <li data-index="rs-73" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="http://works.themepunch.com/revolution_5_3/wp-content/" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli active-revslide" style="perspective: 6000px; width: 100%; height: 100%; overflow: hidden; z-index: 20; visibility: inherit; opacity: 1; background-color: rgba(255, 255, 255, 0);">
                    <!-- MAIN IMAGE -->
                    <div class="slotholder" style="position: absolute; top: 0px; left: 0px; z-index: 0; width: 100%; height: 100%; visibility: inherit; opacity: 1; transform: matrix(1, 0, 0, 1, 0, 0);"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="assets/images/slider/slider_intro_1.jpg" data-kenburns="on" data-duration="5000" data-ease="Power3.easeInOut" data-scalestart="110" data-scaleend="100" data-rotatestart="0" style="background:linear-gradient(90deg, rgba(134,143,150,1) 0%, rgba(89,97,100,1) 100%)" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg defaultimg" data-no-retina="">--><div class="tp-dottedoverlay black"></div><div class="tp-bgimg defaultimg " data-bgcolor="undefined" style="background-repeat: no-repeat; background-image: url(&quot;assets/images/slider/  &quot;); background-size: cover; background-position: center center; width: 100%; height: 100%; opacity: 1; visibility: inherit; z-index: 20;" src="assets/images/slider/"></div><div class="tp-kbimg-wrap " style="z-index: 2; width: 100%; height: 100%; top: 0px; left: 0px; position: absolute; transform: translate3d(0px, 0px, 0px); transform-origin: 0% 0% 0px;"><img class="tp-kbimg"  @foreach($data as $val) @if($val->Name == 'Slide_banner_1') src="assets/images/slider/{{$val->Value}}" @endif @endforeach style="position: absolute; width: 1324px; transform: translate3d(0px, 0px, 0px); transform-origin: 0% 0% 0px;" width="undefined" height="undefined"></div></div>
                    <!-- LAYERS -->
                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 114px; top: 289px; z-index: 6;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption tp-resizeme" id="slide-73-layer-1" data-x="['left','left','left','left']" data-hoffset="['120','120','120','40']" data-y="['middle','middle','middle','middle']" data-voffset="['40','0','-40','-50']" data-width="['440','180','180','100']" data-fontsize="['40','40','40','30']" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:400,&quot;speed&quot;:750,&quot;sfxcolor&quot;:&quot;#98cb46&quot;,&quot;sfx_effect&quot;:&quot;blockfromleft&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;sfxcolor&quot;:&quot;#ffffff&quot;,&quot;sfx_effect&quot;:&quot;blocktoleft&quot;,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;z:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; color: rgb(255, 255, 255); font-size: 38px; font-weight: 700; font-family: Roboto; visibility: inherit; transition: none 0s ease 0s; text-align: inherit; line-height: 64px; border-width: 0px; margin: 0px; padding: 0px; letter-spacing: 0px; white-space: nowrap; min-height: 0px; min-width: 416px; max-height: none; max-width: 416px; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                        Vì thú cưng, không ngừng vươn tới </div><div class="tp-blockmask" style="background: rgb(152, 203, 70); transform: matrix(0, 0, 0, 1, 0, 0); transform-origin: 100% 50% 0px;"></div></div></div></div>
                    <!-- LAYER NR. 1 -->
                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 95px; top: 207px; z-index: 8;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption tp-resizeme" id="slide-73-layer-2" data-x="['left','left','left','left']" data-hoffset="['100','100','100','20']" data-y="['middle','middle','middle','middle']" data-voffset="['20','-20','-60','-50']" data-fontsize="['70','70','60','50']" data-lineheight="['70','70','70','50']" data-width="['600','650','620','380']" data-height="['200','200','200','200']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:200,&quot;speed&quot;:750,&quot;sfxcolor&quot;:&quot;#98cb46&quot;,&quot;sfx_effect&quot;:&quot;blockfromleft&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;sfxcolor&quot;:&quot;#ffffff&quot;,&quot;sfx_effect&quot;:&quot;blocktoleft&quot;,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;z:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[20,20,20,20]" data-paddingright="[20,20,20,20]" data-paddingbottom="[30,30,30,30]" data-paddingleft="[20,20,20,20]" style="z-index: 8; font-family: Roboto; min-width: 567px; max-width: 567px; white-space: normal; font-size: 66px; line-height: 66px; color: rgb(255, 255, 255); letter-spacing: -2px; font-weight: 700; visibility: inherit; transition: none 0s ease 0s; text-align: left; border-width: 0px; margin: 0px; padding: 19px 19px 28px; min-height: 189px; max-height: 189px; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                        Bệnh viện Petpro </div><div class="tp-blockmask" style="background: rgb(152, 203, 70); transform: matrix(0, 0, 0, 1, 0, 0); transform-origin: 100% 50% 0px;"></div></div></div></div>
                    <!-- LAYER NR. 1 -->
                    <div class="tp-parallax-wrap" style="position: absolute; display: block; visibility: visible; left: 114px; top: 411px; z-index: 5;"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position: absolute; display: block; overflow: visible;"><div class="tp-caption btn-theme bg-orange btn-shadow rs-hover-ready" id="slide-73-layer-4" data-x="['left','left','left','left']" data-hoffset="['120','120','120','40']" data-y="['middle','middle','middle','middle']" data-voffset="['160','120','80','60']" data-width="['180','180','180','130']" data-height="none" data-whitespace="normal" data-type="button" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:500,&quot;speed&quot;:1000,&quot;sfxcolor&quot;:&quot;#98cb46&quot;,&quot;sfx_effect&quot;:&quot;blockfromleft&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;sfxcolor&quot;:&quot;#ffffff&quot;,&quot;sfx_effect&quot;:&quot;blocktoleft&quot;,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;z:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;0&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(0,0,0);bg:rgb(255,255,255);&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[30,30,30,20]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[30,30,30,20]" data-fontsize="['18','18','18','14']" style="z-index: 5; white-space: normal; font-size: 17px; line-height: 47px; color: rgb(255, 255, 255); font-family: Roboto; box-sizing: border-box; cursor: pointer; font-weight: 600; text-transform: uppercase; box-shadow: rgb(33, 49, 132) 0px 4px 13px 0px; background: rgb(33, 49, 132); visibility: inherit; transition: none 0s ease 0s; text-align: center; border-width: 0px; margin: 0px; padding: 0px 28px; letter-spacing: 0px; min-height: 0px; min-width: 170px; max-height: none; max-width: 170px; opacity: 1; transform: matrix3d(1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1); transform-origin: 50% 50% 0px;">
                        Liên hệ </div><div class="tp-blockmask" style="background: rgb(152, 203, 70); transform: matrix(0, 0, 0, 1, 0, 0); transform-origin: 100% 50% 0px;"></div></div></div></div>
                </li>
                <!-- SLIDE  -->
                <li data-index="rs-75" data-transition="fade" data-slotamount="default" data-hideafterloop="0" data-hideslideonmobile="off" data-easein="default" data-easeout="default" data-masterspeed="300" data-thumb="http://works.themepunch.com/revolution_5_3/wp-content/" data-rotate="0" data-saveperformance="off" data-title="Slide" data-param1="" data-param2="" data-param3="" data-param4="" data-param5="" data-param6="" data-param7="" data-param8="" data-param9="" data-param10="" data-description="" class="tp-revslider-slidesli" style="perspective: 6000px; width: 100%; height: 100%; overflow: hidden;">
                    <!-- MAIN IMAGE -->
                    <div class="slotholder" style="position:absolute; top:0px; left:0px; z-index:0;width:100%;height:100%;"><!--Runtime Modification - Img tag is Still Available for SEO Goals in Source - <img src="assets/images/slider/slider_intro_2.jpg" data-kenburns="on" data-duration="5000" data-ease="Power3.easeInOut" data-scalestart="110" data-scaleend="100" data-rotatestart="0" data-bgcolor="linear-gradient(180deg, rgba(22,160,133,1) 0%, rgba(244,208,63,1) 100%)" style="background:linear-gradient(180deg, rgba(22,160,133,1) 0%, rgba(244,208,63,1) 100%)" alt="" data-bgposition="center center" data-bgfit="cover" data-bgrepeat="no-repeat" data-bgparallax="off" class="rev-slidebg defaultimg" data-no-retina="">--><div class="tp-dottedoverlay black"></div><div class="tp-bgimg defaultimg " data-bgcolor="linear-gradient(180deg, rgba(22,160,133,1) 0%, rgba(244,208,63,1) 100%)" style="background: linear-gradient(rgb(22, 160, 133) 0%, rgb(244, 208, 63) 100%); width: 100%; height: 100%; opacity: 0;" src="assets/images/slider/slider_intro_2.jpg"></div></div>
                    <!-- LAYERS -->
                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption tp-resizeme" id="slide-73-layer-1_6186" data-x="['left','left','left','left']" data-hoffset="['120','120','120','40']" data-y="['middle','middle','middle','middle']" data-voffset="['40','0','-40','-50']" data-width="['440','180','180','100']" data-fontsize="['40','40','40','30']" data-whitespace="nowrap" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:400,&quot;speed&quot;:750,&quot;sfxcolor&quot;:&quot;#98cb46&quot;,&quot;sfx_effect&quot;:&quot;blockfromleft&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;sfxcolor&quot;:&quot;#ffffff&quot;,&quot;sfx_effect&quot;:&quot;blocktoleft&quot;,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;z:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['inherit','inherit','inherit','inherit']" data-paddingtop="[0,0,0,0]" data-paddingright="[0,0,0,0]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[0,0,0,0]" style="z-index: 6; color: rgb(255, 255, 255); font-size: 40px; font-weight: 700; font-family: Roboto; visibility: hidden;">
                        Vì thú cưng, không ngừng vươn tới </div></div></div></div>
                    <!-- LAYER NR. 1 -->
                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption tp-resizeme" id="slide-73-layer-2_724" data-x="['left','left','left','left']" data-hoffset="['100','100','100','20']" data-y="['middle','middle','middle','middle']" data-voffset="['20','-20','-60','-50']" data-fontsize="['70','70','60','50']" data-lineheight="['70','70','70','50']" data-width="['600','650','620','380']" data-height="['200','200','200','200']" data-whitespace="normal" data-type="text" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:200,&quot;speed&quot;:750,&quot;sfxcolor&quot;:&quot;#98cb46&quot;,&quot;sfx_effect&quot;:&quot;blockfromleft&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;sfxcolor&quot;:&quot;#ffffff&quot;,&quot;sfx_effect&quot;:&quot;blocktoleft&quot;,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;z:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;}]" data-textalign="['left','left','left','left']" data-paddingtop="[20,20,20,20]" data-paddingright="[20,20,20,20]" data-paddingbottom="[30,30,30,30]" data-paddingleft="[20,20,20,20]" style="z-index: 8; font-family: Roboto; min-width: 650px; max-width: 650px; white-space: normal; font-size: 80px; line-height: 70px; color: rgb(255, 255, 255); letter-spacing: -2px; font-weight: 700; visibility: hidden;">
                        Bệnh viện Petpro </div></div></div></div>
                    <!-- LAYER NR. 1 -->
                    <div class="tp-parallax-wrap " style=" position:absolute;display:block;;visibility:hidden"><div class="tp-loop-wrap" style="position:absolute;display:block;;"><div class="tp-mask-wrap" style="position:absolute;display:block;;"><div class="tp-caption btn-theme bg-orange btn-shadow" id="slide-73-layer-4_685" data-x="['left','left','left','left']" data-hoffset="['120','120','120','40']" data-y="['middle','middle','middle','middle']" data-voffset="['160','120','80','60']" data-width="['180','180','180','130']" data-height="none" data-whitespace="normal" data-type="button" data-responsive_offset="on" data-frames="[{&quot;delay&quot;:500,&quot;speed&quot;:1000,&quot;sfxcolor&quot;:&quot;#98cb46&quot;,&quot;sfx_effect&quot;:&quot;blockfromleft&quot;,&quot;frame&quot;:&quot;0&quot;,&quot;from&quot;:&quot;z:0;&quot;,&quot;to&quot;:&quot;o:1;&quot;,&quot;ease&quot;:&quot;Power3.easeInOut&quot;},{&quot;delay&quot;:&quot;wait&quot;,&quot;speed&quot;:500,&quot;sfxcolor&quot;:&quot;#ffffff&quot;,&quot;sfx_effect&quot;:&quot;blocktoleft&quot;,&quot;frame&quot;:&quot;999&quot;,&quot;to&quot;:&quot;z:0;&quot;,&quot;ease&quot;:&quot;Power4.easeOut&quot;},{&quot;frame&quot;:&quot;hover&quot;,&quot;speed&quot;:&quot;0&quot;,&quot;ease&quot;:&quot;Linear.easeNone&quot;,&quot;to&quot;:&quot;o:1;rX:0;rY:0;rZ:0;z:0;&quot;,&quot;style&quot;:&quot;c:rgb(0,0,0);bg:rgb(255,255,255);&quot;}]" data-textalign="['center','center','center','center']" data-paddingtop="[0,0,0,0]" data-paddingright="[30,30,30,20]" data-paddingbottom="[0,0,0,0]" data-paddingleft="[30,30,30,20]" data-fontsize="['18','18','18','14']" style="z-index: 5; white-space: normal; font-size: 18px; line-height: 50px; color: rgb(255, 255, 255); font-family: Roboto; box-sizing: border-box; cursor: pointer; font-weight: 600; text-transform: uppercase; box-shadow: rgb(33, 49, 132) 0px 4px 13px 0px; background: rgb(33, 49, 132); visibility: hidden;">
                        Liên hệ </div></div></div></div>
                    <!-- LAYER NR. 1 -->

                </li>
            </ul>
            <div class="tp-bannertimer" style="height: 5px; background: rgba(255, 255, 255, 0.15); width: 28.0889%; visibility: visible; transform: translate3d(0px, 0px, 0px);"></div>

        <div class="tp-loader spinner0" style="display: none;"><div class="dot1"></div><div class="dot2"></div><div class="bounce1"></div><div class="bounce2"></div><div class="bounce3"></div></div><div class="tp-leftarrow tparrows metis" style="top: 50%; transform: matrix(1, 0, 0, 1, 15, -30); left: 0px;"></div><div class="tp-rightarrow tparrows metis" style="top: 50%; transform: matrix(1, 0, 0, 1, -75, -30); left: 100%;"></div></div>
        <div class="owl-dots"><button role="button" class="owl-dot active"><span></span></button><button role="button" class="owl-dot"><span></span></button><button role="button" class="owl-dot"><span></span></button></div>
    </div>
</section>